version: "3"
services:
  postgres:
    image: "postgres:latest"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 8080:8080 # map 8080 on our local machine to the port inside the docker container
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
